server:
  port: 8081
auth-token:
  header: x-api-key
  value: finansalTeknolojiler

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/exchange
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true