server:
  port: ${PORT:8085}
spring:
  mustache:
    check-template-location: false
logging:
  level:
    org:
      atmosphere: warn
vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
