server:
  port: 8080
spring:
  sql: # ikinci açılışta yorum satırına alınmalı
      init: #
        mode: always #
        data-locations: classpath:/data.sql #

  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: ufuksecretkey
